name: Trigger auto deployment for myhtmxwebsite

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myhtmxwebsite-AutoDeployTrigger-ff974d51-d9cb-4e01-8f8f-b92548d4d350.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYHTMXWEBSITE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYHTMXWEBSITE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYHTMXWEBSITE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: 'Dockerfile' # Ensure your Dockerfile is in the root, or provide the correct path
          registryUrl: rpkcontainers.azurecr.io
          registryUsername: ${{ secrets.MYHTMXWEBSITE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYHTMXWEBSITE_REGISTRY_PASSWORD }}
          containerAppName: myhtmxwebsite
          resourceGroup: rpk-websites
          imageToBuild: rpkcontainers.azurecr.io/myhtmxwebsite:${{ github.sha }}
          buildArguments: |
            --build-arg BASE_IMAGE=mcr.microsoft.com/dotnet/aspnet:9.0-bookworm-slim # Update to a valid and existing .NET image